title: AZ News - новости, актуальные события
name: AZ News
description: Азербайджан, новости, актуальные события в стране и мире
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins: 
  - jekyll-paginate-v2
  
category_dir: blog
pagination:
  enable: true
  per_page: 10
  title: ':title - страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2

exlude: ['node_modules', 'gulpfile.js', 'package.json', 'package-lock.json', 'js/common.js', 'npm-debug.log', '**/Thumbs.db', 'libs', 'sass']

soc: 
  <li><a href="#"><i class="fa fa-facebook"></i></a></li>
  <li><a href="#"><i class="fa fa-twitter"></i></a></li>
  <li><a href="#"><i class="fa fa-instagram"></i></a></li>
  <li><a href="#"><i class="fa fa-rss"></i></a></li>

copyright: Копирование и размещение контента запрещено

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
